/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-21T21:06:59.102Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "64c0cefa-b40a-46fb-878e-d62c1fd14139",
    name: "Nail Art & Care",
    slug: "nail-art--care",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "0e0484d9-37d9-483e-84f1-22a1f1b5164d",
        name: "Acrylic Nails",
        slug: "acrylic-nails",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4c427cfd-4428-43b8-ac2b-55597d685064",
        name: "Gel Nails",
        slug: "gel-nails",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "6ed443ea-a77c-4476-9021-303125adf26c",
        name: "Holiday Nail Ideas",
        slug: "holiday-nail-ideas",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "656b322a-7121-4f99-9ec4-fe3b5337ce43",
        name: "Nail Trends",
        slug: "nail-trends",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "d1a11af6-643e-4120-8ccd-9930dd3d0d4b",
        name: "Nail Tutorials",
        slug: "nail-tutorials",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "aa03a08c-8fd1-493b-8801-0cbe107884b6",
    name: "Makeup & Skincare",
    slug: "makeup--skincare",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "8d84731c-416a-40ad-8ac4-7e32cc729d6c",
        name: "Makeup Tutorials",
        slug: "makeup-tutorials",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "bf6867c2-d850-4cf7-a421-3de8a0fed987",
        name: "Skincare Reviews",
        slug: "skincare-reviews",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "fd156ac6-809b-4819-b78a-5cd85bd79a11",
        name: "Holiday Glam",
        slug: "holiday-glam",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "0b2fdc84-cb3f-43d3-b3bd-4bad5dc0930c",
        name: "Face Makeup",
        slug: "face-makeup",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "6b52a1c9-8854-4624-8619-d5c8193d6595",
        name: "Eye Makeup",
        slug: "eye-makeup",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "4bd29a91-aa21-456c-8295-3cdb6a38d405",
    name: "Hair Care & Styling",
    slug: "hair-care--styling",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "4f9badef-69ea-491e-809f-bcfe37f56989",
        name: "Shampoos & Conditioners",
        slug: "shampoos--conditioners",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "328eaa49-75b3-449e-a11c-700f72372d10",
        name: "Hair Styling Tools",
        slug: "hair-styling-tools",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "f337d861-ebe4-4171-a7a8-2f8fb0b06586",
        name: "Hair Trends",
        slug: "hair-trends",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "b0f60b06-2d6b-483f-a561-3631abc4c415",
        name: "Braid Ideas",
        slug: "braid-ideas",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "0308f712-a2ad-4ae0-9725-d85975b9f6b0",
        name: "Hair Care Tips",
        slug: "hair-care-tips",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "c678ad12-9826-4d4f-be16-5008367a7ee9",
    name: "Fashion & Style",
    slug: "fashion--style",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "ac8a1f4d-0c9e-4ed6-81be-b6b2c47b731b",
        name: "Style Guides",
        slug: "style-guides",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c5fe00de-844d-4f73-8a44-b98cb1518e38",
        name: "Celebrity Fashion",
        slug: "celebrity-fashion",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c05276db-98ad-4b5b-b5ad-b118af893702",
        name: "Holiday Fashion",
        slug: "holiday-fashion",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "de410977-720b-471c-b8f2-c0349970e83d",
        name: "Fashion Trends",
        slug: "fashion-trends",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "b90aa210-e79b-4c02-86c4-9cf96b3dd396",
        name: "Accessories",
        slug: "accessories",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
