/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: GlamSphere
 * Generated: 2025-12-21T21:06:59.101Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "512a985e-e13e-4200-8dbd-075390b7b092",
    name: "GlamSphere",
    description: "GlamSphere delivers cutting-edge beauty insights and personalized style solutions through expert-driven content, product innovations, and trendsetting inspiration.",
    url: "https://glamsphere.org",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Elevate your style game with expert beauty and fashion insights"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to GlamSphere",
    subtitle: "Elevate your style game with expert beauty and fashion insights"
  },

  // Default author information
  author: {
    name: "GlamSphere Team",
    bio: "GlamSphere delivers cutting-edge beauty insights and personalized style solutions through expert-driven content, product innovations, and trendsett...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Beauty & Fashion Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from GlamSphere delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Style Guides",
      icon: "BookOpen",
      slug: "style-guides"
    },
    { 
      name: "Nail Art & Care",
      icon: "FileText",
      slug: "nail-art--care"
    },
    { 
      name: "Makeup Tutorials",
      icon: "GraduationCap",
      slug: "makeup-tutorials"
    },
    { 
      name: "Acrylic Nails",
      icon: "FileText",
      slug: "acrylic-nails"
    },
    { 
      name: "Shampoos & Conditioners",
      icon: "FileText",
      slug: "shampoos--conditioners"
    },
    { 
      name: "Gel Nails",
      icon: "FileText",
      slug: "gel-nails"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "0d474705-7b89-424f-871e-593065ca825e",
      name: "Amara Johnson",
      bio: "Amara brings a vibrant and conversational writing style to her celebrity beauty features and expert interviews. Her content is peppered with insider knowledge and a touch of glamour, making her pieces a must-read for those seeking the latest in celebrity trends. Amara's background in entertainment journalism enhances her ability to connect with readers and deliver compelling, star-studded stories.",
      image: "/authors/0d474705-7b89-424f-871e-593065ca825e.jpg",
      role: "Celebrity Beauty Correspondent"
    },
    {
      id: "eca0e8ec-5947-439a-91f7-1fff34a17cd5",
      name: "Jasper Lee",
      bio: "Jasper's writing blends creativity with professionalism, offering readers a polished yet personable perspective on fashion and beauty. He excels at crafting how-to tutorials and seasonal inspiration galleries that inspire readers to experiment with their style. With years of experience in the fashion industry, Jasper's articles are both authoritative and relatable, providing readers with actionable style solutions.",
      image: "/authors/eca0e8ec-5947-439a-91f7-1fff34a17cd5.jpg",
      role: "Fashion and Beauty Editor"
    },
    {
      id: "06bbc365-b9aa-46d6-919c-d33ea113e9ff",
      name: "Sophia Ellis",
      bio: "Sophia writes with a keen eye for detail and a knack for predicting the next big trend in the beauty world. Her content is infused with insightful analysis and a touch of wit, making complex beauty concepts accessible and engaging. With a background in cosmetic science, Sophia is the go-to expert for deep dives into product innovations and trend guides.",
      image: "/authors/06bbc365-b9aa-46d6-919c-d33ea113e9ff.jpg",
      role: "Beauty Innovator and Trend Analyst"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
